package com.uniClub.exceptions.exception;

import lombok.Getter;

@Getter
public enum MessageType {

    /* ---------- GENEL / SİSTEM ---------- */
    GENERAL_EXCEPTION("9999", "GENERAL_EXCEPTION"),
    VALIDATION_ERROR("1001", "VALIDATION_ERROR"),
    INTERNAL_SERVER_ERROR("1002", "INTERNAL_SERVER_ERROR"),
    METHOD_NOT_ALLOWED("1003", "METHOD_NOT_ALLOWED"),
    BAD_REQUEST("1004", "BAD_REQUEST"),
    SERVICE_UNAVAILABLE("1005", "SERVICE_UNAVAILABLE"),
    JSON_PARSE_ERROR("1006", "JSON_PARSE_ERROR"),
    DATA_INTEGRITY_VIOLATION("1007", "DATA_INTEGRITY_VIOLATION"),
    ENTITY_MAPPING_ERROR("1008", "ENTITY_MAPPING_ERROR"),
    REQUEST_TIMEOUT("1009", "REQUEST_TIMEOUT"),

    /* ---------- DATABASE & MIGRATION ---------- */
    NO_RECORD_EXIST("2000", "RECORD_IS_NOT_EXIST"),
    DUPLICATE_RECORD("2001", "DUPLICATE_RECORD"),
    FOREIGN_KEY_CONSTRAINT("2002", "FOREIGN_KEY_CONSTRAINT_VIOLATION"),
    DATABASE_CONNECTION_ERROR("2003", "DATABASE_CONNECTION_ERROR"),
    MIGRATION_CHECKSUM_MISMATCH("2004", "MIGRATION_CHECKSUM_MISMATCH"),
    TRANSACTION_FAILED("2005", "TRANSACTION_FAILED"),

    /* ---------- AUTH / JWT / SECURITY ---------- */
    USERNAME_NOT_FOUND("3000", "USERNAME_NOT_FOUND"),
    INVALID_CREDENTIALS("3001", "INVALID_CREDENTIALS"),
    ACCOUNT_LOCKED("3002", "ACCOUNT_LOCKED"),
    TOKEN_EXPIRED("3003", "TOKEN_EXPIRED"),
    TOKEN_INVALID("3004", "TOKEN_INVALID"),
    TOKEN_MISSING("3005", "TOKEN_MISSING"),
    UNAUTHORIZED_ACCESS("3006", "UNAUTHORIZED_ACCESS"),
    ACCESS_DENIED("3007", "ACCESS_DENIED"),
    REFRESH_TOKEN_EXPIRED("3008", "REFRESH_TOKEN_EXPIRED"),
    INVALID_REFRESH_TOKEN("3009", "INVALID_REFRESH_TOKEN"),
    PASSWORD_MISMATCH("3010", "PASSWORD_MISMATCH"),
    PASSWORD_POLICY_VIOLATION("3011", "PASSWORD_POLICY_VIOLATION"),

    /* ---------- USER OPERATIONS ---------- */
    USER_ALREADY_EXISTS("4000", "USER_ALREADY_EXISTS"),
    USER_NOT_FOUND("4001", "USER_NOT_FOUND"),
    USER_REGISTRATION_FAILED("4002", "USER_REGISTRATION_FAILED"),
    USER_UPDATE_FAILED("4003", "USER_UPDATE_FAILED"),
    USER_DELETION_FAILED("4004", "USER_DELETION_FAILED"),
    EMAIL_ALREADY_EXISTS("4005", "EMAIL_ALREADY_EXISTS"),
    USER_NOT_ACTIVE("4006", "USER_NOT_ACTIVE"),
    INVALID_ROLE("4007", "INVALID_ROLE"),

    /* ---------- EVENT / CLUB OPERATIONS ---------- */
    EVENT_NOT_FOUND("5000", "EVENT_NOT_FOUND"),
    EVENT_ALREADY_EXISTS("5001", "EVENT_ALREADY_EXISTS"),
    EVENT_REGISTRATION_CLOSED("5002", "EVENT_REGISTRATION_CLOSED"),
    EVENT_CAPACITY_FULL("5003", "EVENT_CAPACITY_FULL"),
    EVENT_CREATION_FAILED("5004", "EVENT_CREATION_FAILED"),
    EVENT_UPDATE_FAILED("5005", "EVENT_UPDATE_FAILED"),
    EVENT_DELETE_FAILED("5006", "EVENT_DELETE_FAILED"),




    // 🔽 Yeni eklenen detaylı event hata tipleri
    EVENT_DATE_INVALID("5007", "EVENT_DATE_INVALID"),
    EVENT_LOCATION_NOT_FOUND("5008", "EVENT_LOCATION_NOT_FOUND"),
    EVENT_USER_NOT_OWNER("5009", "EVENT_USER_NOT_OWNER"),
    EVENT_ALREADY_PASSED("5010", "EVENT_ALREADY_PASSED"),
    EVENT_ATTENDEE_NOT_FOUND("5011", "EVENT_ATTENDEE_NOT_FOUND"),
    EVENT_ATTENDEE_ALREADY_JOINED("5012", "EVENT_ATTENDEE_ALREADY_JOINED"),
    EVENT_ATTENDEE_LIMIT_EXCEEDED("5013", "EVENT_ATTENDEE_LIMIT_EXCEEDED"),
    EVENT_UNAUTHORIZED_ACCESS("5014", "EVENT_UNAUTHORIZED_ACCESS"),
    EVENT_SAVE_DATABASE_ERROR("5015", "EVENT_SAVE_DATABASE_ERROR"),
    EVENT_TIME_CONFLICT("5016", "EVENT_TIME_CONFLICT"),
    EVENT_DATA_INCONSISTENCY("5017", "EVENT_DATA_INCONSISTENCY"),
    EVENT_REMINDER_SEND_FAILED("5018", "EVENT_REMINDER_SEND_FAILED"),
    EVENT_NOTIFICATION_ERROR("5019", "EVENT_NOTIFICATION_ERROR"),
    EVENT_DEADLINE_EXPIRED("5020", "EVENT_DEADLINE_EXPIRED"),



    /* ---------- CLUB OPERATIONS ---------- */
    CLUB_NOT_FOUND("5500", "CLUB_NOT_FOUND"),
    CLUB_ALREADY_EXISTS("5501", "CLUB_ALREADY_EXISTS"),
    CLUB_CREATION_FAILED("5502", "CLUB_CREATION_FAILED"),
    CLUB_UPDATE_FAILED("5503", "CLUB_UPDATE_FAILED"),
    CLUB_DELETE_FAILED("5504", "CLUB_DELETE_FAILED"),
    CLUB_NOT_APPROVED("5505", "CLUB_NOT_APPROVED"),
    CLUB_ALREADY_APPROVED("5506", "CLUB_ALREADY_APPROVED"),
    CLUB_PRESIDENT_NOT_FOUND("5507", "CLUB_PRESIDENT_NOT_FOUND"),
    CLUB_PRESIDENT_ALREADY_ASSIGNED("5508", "CLUB_PRESIDENT_ALREADY_ASSIGNED"),
    CLUB_MEMBER_NOT_FOUND("5509", "CLUB_MEMBER_NOT_FOUND"),
    CLUB_MEMBER_ALREADY_EXISTS("5510", "CLUB_MEMBER_ALREADY_EXISTS"),
    CLUB_MEMBERSHIP_LIMIT_EXCEEDED("5511", "CLUB_MEMBERSHIP_LIMIT_EXCEEDED"),
    CLUB_MEMBER_REMOVE_FAILED("5512", "CLUB_MEMBER_REMOVE_FAILED"),
    CLUB_NOT_OWNER("5513", "CLUB_NOT_OWNER"),
    CLUB_ACCESS_DENIED("5514", "CLUB_ACCESS_DENIED"),
    CLUB_EVENT_NOT_FOUND("5515", "CLUB_EVENT_NOT_FOUND"),
    CLUB_EVENT_ALREADY_LINKED("5516", "CLUB_EVENT_ALREADY_LINKED"),
    CLUB_EVENT_LINK_FAILED("5517", "CLUB_EVENT_LINK_FAILED"),
    CLUB_EVENT_UNLINK_FAILED("5518", "CLUB_EVENT_UNLINK_FAILED"),
    CLUB_DATA_INCONSISTENCY("5519", "CLUB_DATA_INCONSISTENCY"),
    CLUB_SAVE_DATABASE_ERROR("5520", "CLUB_SAVE_DATABASE_ERROR"),
    CLUB_EMAIL_ALREADY_EXISTS("5521", "CLUB_EMAIL_ALREADY_EXISTS"),
    CLUB_INSTAGRAM_ALREADY_EXISTS("5522", "CLUB_INSTAGRAM_ALREADY_EXISTS"),


    /* ---------- SERVICE / REPOSITORY / LOGIC ---------- */
    SERVICE_CALL_FAILED("6000", "SERVICE_CALL_FAILED"),
    REPOSITORY_OPERATION_FAILED("6001", "REPOSITORY_OPERATION_FAILED"),
    CONVERSION_FAILED("6002", "DTO_ENTITY_CONVERSION_FAILED"),
    NULL_POINTER("6003", "NULL_POINTER_EXCEPTION"),
    ILLEGAL_ARGUMENT("6004", "ILLEGAL_ARGUMENT_EXCEPTION"),
    UNSUPPORTED_OPERATION("6005", "UNSUPPORTED_OPERATION"),

    /* ---------- NOTIFICATION OPERATIONS ---------- */
    NOTIFICATION_NOT_FOUND("7000", "NOTIFICATION_NOT_FOUND"),
    NOTIFICATION_CREATION_FAILED("7001", "NOTIFICATION_CREATION_FAILED"),
    NOTIFICATION_UPDATE_FAILED("7002", "NOTIFICATION_UPDATE_FAILED"),
    NOTIFICATION_DELETE_FAILED("7003", "NOTIFICATION_DELETE_FAILED"),
    NOTIFICATION_SEND_FAILED("7004", "NOTIFICATION_SEND_FAILED"),
    NOTIFICATION_MARK_AS_READ_FAILED("7005", "NOTIFICATION_MARK_AS_READ_FAILED"),
    NOTIFICATION_FETCH_FAILED("7006", "NOTIFICATION_FETCH_FAILED"),
    NOTIFICATION_USER_NOT_FOUND("7007", "NOTIFICATION_USER_NOT_FOUND"),
    NOTIFICATION_TYPE_INVALID("7008", "NOTIFICATION_TYPE_INVALID"),
    NOTIFICATION_TARGET_MISSING("7009", "NOTIFICATION_TARGET_MISSING"),
    NOTIFICATION_DATABASE_ERROR("7010", "NOTIFICATION_DATABASE_ERROR"),
    NOTIFICATION_CONVERSION_ERROR("7011", "NOTIFICATION_CONVERSION_ERROR"),
    NOTIFICATION_EVENT_LINK_FAILED("7012", "NOTIFICATION_EVENT_LINK_FAILED"),
    NOTIFICATION_PERMISSION_DENIED("7013", "NOTIFICATION_PERMISSION_DENIED"),
    NOTIFICATION_UNREAD_FETCH_FAILED("7014", "NOTIFICATION_UNREAD_FETCH_FAILED"),

    ALREADY_JOINED("8000", "ALREADY_JOINED"),
    NOT_PARTICIPANT("8001", "NOT_PARTICIPANT");


    private final String code;
    private final String message;

    MessageType(String code, String message) {
        this.code = code;
        this.message = message;
    }
}
