package com.uniClub.exceptions.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum MessageType {

    /* ---------- GENEL / SİSTEM ---------- */
    GENERAL_EXCEPTION("9999", "GENERAL_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    VALIDATION_ERROR("1001", "VALIDATION_ERROR", HttpStatus.BAD_REQUEST),
    INTERNAL_SERVER_ERROR("1002", "INTERNAL_SERVER_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    METHOD_NOT_ALLOWED("1003", "METHOD_NOT_ALLOWED", HttpStatus.METHOD_NOT_ALLOWED),
    BAD_REQUEST("1004", "BAD_REQUEST", HttpStatus.BAD_REQUEST),
    SERVICE_UNAVAILABLE("1005", "SERVICE_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE),
    JSON_PARSE_ERROR("1006", "JSON_PARSE_ERROR", HttpStatus.BAD_REQUEST),
    DATA_INTEGRITY_VIOLATION("1007", "DATA_INTEGRITY_VIOLATION", HttpStatus.CONFLICT),
    ENTITY_MAPPING_ERROR("1008", "ENTITY_MAPPING_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    REQUEST_TIMEOUT("1009", "REQUEST_TIMEOUT", HttpStatus.REQUEST_TIMEOUT),

    /* ---------- DATABASE & MIGRATION ---------- */
    NO_RECORD_EXIST("2000", "RECORD_IS_NOT_EXIST", HttpStatus.NOT_FOUND),
    DUPLICATE_RECORD("2001", "DUPLICATE_RECORD", HttpStatus.CONFLICT),
    FOREIGN_KEY_CONSTRAINT("2002", "FOREIGN_KEY_CONSTRAINT_VIOLATION", HttpStatus.BAD_REQUEST),
    DATABASE_CONNECTION_ERROR("2003", "DATABASE_CONNECTION_ERROR", HttpStatus.SERVICE_UNAVAILABLE),
    MIGRATION_CHECKSUM_MISMATCH("2004", "MIGRATION_CHECKSUM_MISMATCH", HttpStatus.INTERNAL_SERVER_ERROR),
    TRANSACTION_FAILED("2005", "TRANSACTION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    /* ---------- AUTH / JWT / SECURITY ---------- */
    USERNAME_NOT_FOUND("3000", "USERNAME_NOT_FOUND", HttpStatus.NOT_FOUND),
    INVALID_CREDENTIALS("3001", "INVALID_CREDENTIALS", HttpStatus.UNAUTHORIZED),
    ACCOUNT_LOCKED("3002", "ACCOUNT_LOCKED", HttpStatus.LOCKED),
    TOKEN_EXPIRED("3003", "TOKEN_EXPIRED", HttpStatus.UNAUTHORIZED),
    TOKEN_INVALID("3004", "TOKEN_INVALID", HttpStatus.UNAUTHORIZED),
    TOKEN_MISSING("3005", "TOKEN_MISSING", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED_ACCESS("3006", "UNAUTHORIZED_ACCESS", HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED("3007", "ACCESS_DENIED", HttpStatus.FORBIDDEN),
    REFRESH_TOKEN_EXPIRED("3008", "REFRESH_TOKEN_EXPIRED", HttpStatus.UNAUTHORIZED),
    INVALID_REFRESH_TOKEN("3009", "INVALID_REFRESH_TOKEN", HttpStatus.UNAUTHORIZED),
    PASSWORD_MISMATCH("3010", "PASSWORD_MISMATCH", HttpStatus.BAD_REQUEST),
    PASSWORD_POLICY_VIOLATION("3011", "PASSWORD_POLICY_VIOLATION", HttpStatus.BAD_REQUEST),
    CODE_IS_ERRORS("3012", "CODE_IS_ERRORS", HttpStatus.BAD_REQUEST),
    CODE_TIME_IS_EXPIRES_DATE("3013", "CODE_TIME_IS_EXPIRES_DATE", HttpStatus.GONE),
    CODE_NOT_FOUND("3014", "CODE_NOT_FOUND", HttpStatus.NOT_FOUND),
    ACCOUNT_NOT_VERIFIED("3015", "ACCOUNT_NOT_VERIFIED", HttpStatus.FORBIDDEN),
    PASSWORD_IS_NOT_SAME("3016", "PASSWORD_IS_NOT_SAME", HttpStatus.BAD_REQUEST),
    FILE_NOT_FOUND("3017", "FILE_NOT_FOUND", HttpStatus.NOT_FOUND),

    /* ---------- USER OPERATIONS ---------- */
    USER_ALREADY_EXISTS("4000", "USER_ALREADY_EXISTS", HttpStatus.CONFLICT),
    USER_NOT_FOUND("4001", "USER_NOT_FOUND", HttpStatus.NOT_FOUND),
    USER_REGISTRATION_FAILED("4002", "USER_REGISTRATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_UPDATE_FAILED("4003", "USER_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_DELETION_FAILED("4004", "USER_DELETION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    EMAIL_ALREADY_EXISTS("4005", "EMAIL_ALREADY_EXISTS", HttpStatus.CONFLICT),
    USER_NOT_ACTIVE("4006", "USER_NOT_ACTIVE", HttpStatus.FORBIDDEN),
    INVALID_ROLE("4007", "INVALID_ROLE", HttpStatus.BAD_REQUEST),

    /* ---------- EVENT / CLUB OPERATIONS ---------- */
    EVENT_NOT_FOUND("5000", "EVENT_NOT_FOUND", HttpStatus.NOT_FOUND),
    EVENT_ALREADY_EXISTS("5001", "EVENT_ALREADY_EXISTS", HttpStatus.CONFLICT),
    EVENT_REGISTRATION_CLOSED("5002", "EVENT_REGISTRATION_CLOSED", HttpStatus.BAD_REQUEST),
    EVENT_CAPACITY_FULL("5003", "EVENT_CAPACITY_FULL", HttpStatus.BAD_REQUEST),
    EVENT_CREATION_FAILED("5004", "EVENT_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    EVENT_UPDATE_FAILED("5005", "EVENT_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    EVENT_DELETE_FAILED("5006", "EVENT_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    EVENT_DATE_INVALID("5007", "EVENT_DATE_INVALID", HttpStatus.BAD_REQUEST),
    EVENT_LOCATION_NOT_FOUND("5008", "EVENT_LOCATION_NOT_FOUND", HttpStatus.NOT_FOUND),
    EVENT_USER_NOT_OWNER("5009", "EVENT_USER_NOT_OWNER", HttpStatus.FORBIDDEN),
    EVENT_ALREADY_PASSED("5010", "EVENT_ALREADY_PASSED", HttpStatus.BAD_REQUEST),
    EVENT_ATTENDEE_NOT_FOUND("5011", "EVENT_ATTENDEE_NOT_FOUND", HttpStatus.NOT_FOUND),
    EVENT_ATTENDEE_ALREADY_JOINED("5012", "EVENT_ATTENDEE_ALREADY_JOINED", HttpStatus.CONFLICT),
    EVENT_ATTENDEE_LIMIT_EXCEEDED("5013", "EVENT_ATTENDEE_LIMIT_EXCEEDED", HttpStatus.BAD_REQUEST),
    EVENT_UNAUTHORIZED_ACCESS("5014", "EVENT_UNAUTHORIZED_ACCESS", HttpStatus.FORBIDDEN),
    EVENT_SAVE_DATABASE_ERROR("5015", "EVENT_SAVE_DATABASE_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    EVENT_TIME_CONFLICT("5016", "EVENT_TIME_CONFLICT", HttpStatus.CONFLICT),
    EVENT_DATA_INCONSISTENCY("5017", "EVENT_DATA_INCONSISTENCY", HttpStatus.INTERNAL_SERVER_ERROR),
    EVENT_REMINDER_SEND_FAILED("5018", "EVENT_REMINDER_SEND_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    EVENT_NOTIFICATION_ERROR("5019", "EVENT_NOTIFICATION_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    EVENT_DEADLINE_EXPIRED("5020", "EVENT_DEADLINE_EXPIRED", HttpStatus.BAD_REQUEST),

    /* ---------- CLUB OPERATIONS ---------- */
    CLUB_NOT_FOUND("5500", "CLUB_NOT_FOUND", HttpStatus.NOT_FOUND),
    CLUB_ALREADY_EXISTS("5501", "CLUB_ALREADY_EXISTS", HttpStatus.CONFLICT),
    CLUB_CREATION_FAILED("5502", "CLUB_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    CLUB_UPDATE_FAILED("5503", "CLUB_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    CLUB_DELETE_FAILED("5504", "CLUB_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    CLUB_NOT_APPROVED("5505", "CLUB_NOT_APPROVED", HttpStatus.FORBIDDEN),
    CLUB_ALREADY_APPROVED("5506", "CLUB_ALREADY_APPROVED", HttpStatus.BAD_REQUEST),
    CLUB_PRESIDENT_NOT_FOUND("5507", "CLUB_PRESIDENT_NOT_FOUND", HttpStatus.NOT_FOUND),
    CLUB_PRESIDENT_ALREADY_ASSIGNED("5508", "CLUB_PRESIDENT_ALREADY_ASSIGNED", HttpStatus.CONFLICT),
    CLUB_MEMBER_NOT_FOUND("5509", "CLUB_MEMBER_NOT_FOUND", HttpStatus.NOT_FOUND),
    CLUB_MEMBER_ALREADY_EXISTS("5510", "CLUB_MEMBER_ALREADY_EXISTS", HttpStatus.CONFLICT),
    CLUB_MEMBERSHIP_LIMIT_EXCEEDED("5511", "CLUB_MEMBERSHIP_LIMIT_EXCEEDED", HttpStatus.BAD_REQUEST),
    CLUB_MEMBER_REMOVE_FAILED("5512", "CLUB_MEMBER_REMOVE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    CLUB_NOT_OWNER("5513", "CLUB_NOT_OWNER", HttpStatus.FORBIDDEN),
    CLUB_ACCESS_DENIED("5514", "CLUB_ACCESS_DENIED", HttpStatus.FORBIDDEN),
    CLUB_EVENT_NOT_FOUND("5515", "CLUB_EVENT_NOT_FOUND", HttpStatus.NOT_FOUND),
    CLUB_EVENT_ALREADY_LINKED("5516", "CLUB_EVENT_ALREADY_LINKED", HttpStatus.CONFLICT),
    CLUB_EVENT_LINK_FAILED("5517", "CLUB_EVENT_LINK_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    CLUB_EVENT_UNLINK_FAILED("5518", "CLUB_EVENT_UNLINK_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    CLUB_DATA_INCONSISTENCY("5519", "CLUB_DATA_INCONSISTENCY", HttpStatus.INTERNAL_SERVER_ERROR),
    CLUB_SAVE_DATABASE_ERROR("5520", "CLUB_SAVE_DATABASE_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    CLUB_EMAIL_ALREADY_EXISTS("5521", "CLUB_EMAIL_ALREADY_EXISTS", HttpStatus.CONFLICT),
    CLUB_INSTAGRAM_ALREADY_EXISTS("5522", "CLUB_INSTAGRAM_ALREADY_EXISTS", HttpStatus.CONFLICT),
    REQUEST_ALREADY_EXISTS("5523", "REQUEST_ALREADY_EXISTS", HttpStatus.CONFLICT),
    REQUEST_NOT_FOUND("5524", "REQUEST_NOT_FOUND", HttpStatus.NOT_FOUND),
    APPROVER_NOT_FOUND("5525", "APPROVER_NOT_FOUND", HttpStatus.NOT_FOUND),

    /* ---------- MEMBER OPERATIONS ---------- */
    MEMBER_NOT_FOUND("5800", "MEMBER_NOT_FOUND", HttpStatus.NOT_FOUND),
    MEMBER_ALREADY_EXISTS("5801", "MEMBER_ALREADY_EXISTS", HttpStatus.CONFLICT),
    MEMBER_CREATION_FAILED("5802", "MEMBER_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    MEMBER_UPDATE_FAILED("5803", "MEMBER_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    MEMBER_DELETE_FAILED("5804", "MEMBER_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    MEMBER_NOT_ACTIVE("5805", "MEMBER_NOT_ACTIVE", HttpStatus.FORBIDDEN),
    MEMBER_USER_MISMATCH("5806", "MEMBER_USER_MISMATCH", HttpStatus.BAD_REQUEST),
    MEMBER_DATA_INCONSISTENCY("5807", "MEMBER_DATA_INCONSISTENCY", HttpStatus.INTERNAL_SERVER_ERROR),
    MEMBER_SAVE_DATABASE_ERROR("5808", "MEMBER_SAVE_DATABASE_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    MEMBER_STUDENT_NUMBER_ALREADY_EXISTS("5809", "STUDENT_NUMBER_ALREADY_EXISTS", HttpStatus.CONFLICT),
    MEMBER_INSTAGRAM_ALREADY_EXISTS("5810", "INSTAGRAM_ALREADY_EXISTS", HttpStatus.CONFLICT),
    MEMBER_LINKEDIN_ALREADY_EXISTS("5811", "LINKEDIN_ALREADY_EXISTS", HttpStatus.CONFLICT),
    MEMBER_GITHUB_ALREADY_EXISTS("5812", "GITHUB_ALREADY_EXISTS", HttpStatus.CONFLICT),
    MEMBER_CERTIFICATE_VALIDATION_FAILED("5813", "CERTIFICATE_VALIDATION_FAILED", HttpStatus.BAD_REQUEST),
    MEMBER_LANGUAGE_INVALID("5814", "MEMBER_LANGUAGE_INVALID", HttpStatus.BAD_REQUEST),
    MEMBER_PROJECT_LIST_INVALID("5815", "MEMBER_PROJECT_LIST_INVALID", HttpStatus.BAD_REQUEST),
    MEMBER_IS_NOT_OWNER("5816", "MEMBER_IS_NOT_OWNER", HttpStatus.FORBIDDEN),
    MEMBER_UNAUTHORIZED_ACCESS("5817", "MEMBER_UNAUTHORIZED_ACCESS", HttpStatus.FORBIDDEN),

    /* ---------- SERVICE / REPOSITORY / LOGIC ---------- */
    SERVICE_CALL_FAILED("6000", "SERVICE_CALL_FAILED", HttpStatus.BAD_GATEWAY),
    REPOSITORY_OPERATION_FAILED("6001", "REPOSITORY_OPERATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    CONVERSION_FAILED("6002", "DTO_ENTITY_CONVERSION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    NULL_POINTER("6003", "NULL_POINTER_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    ILLEGAL_ARGUMENT("6004", "ILLEGAL_ARGUMENT_EXCEPTION", HttpStatus.BAD_REQUEST),
    UNSUPPORTED_OPERATION("6005", "UNSUPPORTED_OPERATION", HttpStatus.NOT_IMPLEMENTED),

    /* ---------- NOTIFICATION OPERATIONS ---------- */
    NOTIFICATION_NOT_FOUND("7000", "NOTIFICATION_NOT_FOUND", HttpStatus.NOT_FOUND),
    NOTIFICATION_CREATION_FAILED("7001", "NOTIFICATION_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_UPDATE_FAILED("7002", "NOTIFICATION_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_DELETE_FAILED("7003", "NOTIFICATION_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_SEND_FAILED("7004", "NOTIFICATION_SEND_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_MARK_AS_READ_FAILED("7005", "NOTIFICATION_MARK_AS_READ_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_FETCH_FAILED("7006", "NOTIFICATION_FETCH_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_USER_NOT_FOUND("7007", "NOTIFICATION_USER_NOT_FOUND", HttpStatus.NOT_FOUND),
    NOTIFICATION_TYPE_INVALID("7008", "NOTIFICATION_TYPE_INVALID", HttpStatus.BAD_REQUEST),
    NOTIFICATION_TARGET_MISSING("7009", "NOTIFICATION_TARGET_MISSING", HttpStatus.BAD_REQUEST),
    NOTIFICATION_DATABASE_ERROR("7010", "NOTIFICATION_DATABASE_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_CONVERSION_ERROR("7011", "NOTIFICATION_CONVERSION_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_EVENT_LINK_FAILED("7012", "NOTIFICATION_EVENT_LINK_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_PERMISSION_DENIED("7013", "NOTIFICATION_PERMISSION_DENIED", HttpStatus.FORBIDDEN),
    NOTIFICATION_UNREAD_FETCH_FAILED("7014", "NOTIFICATION_UNREAD_FETCH_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    /* ---------- OTHER ---------- */
    ALREADY_JOINED("8000", "ALREADY_JOINED", HttpStatus.CONFLICT),
    NOT_PARTICIPANT("8001", "NOT_PARTICIPANT", HttpStatus.BAD_REQUEST);


    private final String code;
    private final String message;
    private final HttpStatus httpStatus;

    MessageType(String code, String message, HttpStatus httpStatus) {
        this.code = code;
        this.message = message;
        this.httpStatus = httpStatus;
    }
}